num_classes: 10
labels:
- dresses
- glasses
- gloves
- hats
- pants
- shoes
- shorts
- sweater
- t_shirts
- watches
backbone: dla60x_c
backbone_kwargs: null
head: linear
pretrained: true
loss_fn: null
optimizer: Adam
lr_scheduler: null
metrics: null
learning_rate: null
multi_label: false
training_strategy: default
training_strategy_kwargs: null
